Implement Reddit provider
pocketbase/pocketbase pull request #1936
Opened 2023-02-27 20:06 UTC by stnrd

This MR contains the implementation of the Reddit login provider. 

I have created this MR after a discussion topic I have created 2 weeks ago. 

As mentioned in there is that Reddit only gives sessions for 1 hour and doesn't share email addresses. 

https://github.com/pocketbase/pocketbase/discussions/1851

Just let me know if I need to change something.

2023-02-27 20:30 UTC, ganigeorgiev requested changes
Thanks! I left some minor notes, feel free to check them when you have time.

I'll review and test the provider in more details sometime later this week.

2023-02-27 20:30 UTC, ganigeorgiev commented on tools/auth/reddit.go
> +		Login            string `json:"login"`
What is `Login`?

2023-02-27 20:30 UTC, ganigeorgiev commented on tools/auth/reddit.go
> +// FetchAuthUser returns an AuthUser instance based the Reddit's user api.
If available, could you also add a link to the official user API documentation?

2023-02-27 20:30 UTC, ganigeorgiev commented on tools/auth/reddit.go
> +	fmt.Println(string(data))
The debug statement can be removed if not needed anymore.

2023-02-27 20:30 UTC, ganigeorgiev commented on tools/auth/reddit.go
> +		HasVerifiedEmail bool   `json:"has_verified_email"`
We can remove this field if Reddit doesn't return an email.

2023-02-27 20:30 UTC, ganigeorgiev commented on tools/auth/reddit.go
> +		AccessToken: token.AccessToken,
Add also `RefreshToken: token.RefreshToken,`

2023-02-27 20:30 UTC, ganigeorgiev commented on tools/auth/reddit.go
> +	}
Let's return an error only if the account is suspended, since we don't care about the email in this case.

2023-03-26 08:53 UTC, denizkenan commented
is development on this paused? Should I pick it up?

2023-03-30 11:07 UTC, ganigeorgiev commented
I'm closing this PR since it seems abandoned and it is behind the latest changes.

If someone else want to works on this, feel free to file a new PR against the `develop` branch (ideally addressing the above comments).

2023-03-30 11:07 UTC, closed without merging