Add mailcow OAuth
pocketbase/pocketbase pull request #3364
Opened 2023-09-20 21:32 UTC by thisni1s

I based this on the Patroen PR #3323 and the  Yandex commit 435eca6 .
I will try to add and or fix anything that is missing.
I also tested this with the pocketbase JS SDK and have run `make test` and `make lint`

2023-09-21 05:50 UTC, ganigeorgiev commented
Thank you for the PR but I'm not sure about this integration.

As far as I understand this is a self-hosted only service, right?

Keep in mind that I'm not familiar with mailcow and their documentation lack details about how the OAuth2 is implemented and what flows are supported (eg. PKCE).

I'm also little confused whether this is actually needed because it seems that based on the following PR https://github.com/mailcow/mailcow-dockerized/pull/5381 and the blog post in https://mailcow.email/posts/2023/ldap-announcement/, the mailcow team seems to plan adding support for OIDC. Here is an excerpt from the LDAP blogpost:

> ... **The mailcow is connected to Keycloak via OIDC** ...

_(if I'm reading it correctly they'll add OIDC support to allow Keycloack connecting to mailcow and then use Keyclock for other auth integration like LDAP)_


But the above PR and this OIDC implementation doesn't seem to be merged yet (there is a PR to what they call "nightly" in https://github.com/mailcow/mailcow-dockerized/pull/5387 but I haven't tested it).

---

So at the end, if they ended up adding support for OIDC, the current custom implementation no longer will be needed as PocketBase devs can use the existing generic OIDC provider.

I'll close the PR for now to avoid the cluttering, but feel to correct me if I'm reading the above resources incorrectly and a custom mailcow integration would be definitely required.

2023-09-21 07:32 UTC, thisni1s commented
Hi,
yes mailcow is a self-hosted service only and i made this integration to serve my specific needs :)

Their OAuth2 integration really is badly documented, but it is based upon this PHP library https://bshaffer.github.io/oauth2-server-php-docs/

They will add OIDC support for mailcow, where mailcow acts as the OIDC Client and not as a provider.
So without the direct integration you would have to set up an identity management service like keycloak or authentik as the source of the identities and then have mailcow and pocketbase be the clients of this service instead of having mailcow as the provider and managing all the accounts there.
So their OIDC support would not enable pocketbase users to connect to mailcow without using an additional identity management software, thats why i felt a direct integration would be easier.

Still in theory it will be possible with their OIDC implementation to connect everything together, but you have to use an additional service.

Maybe i could clear some things up, in the end its up to you to decide if the direct integration is worth it or not.

2023-09-21 08:12 UTC, ganigeorgiev requested changes
I this case I guess it makes sense to have a custom provider.

I've added some nitpicks but keep in mind that this PR remains with a low priority and I'll have to find time to setup a local mailcow instance to test it (_the client-side `OIDCOptions` and `SelfHostedOptions` could also be merged but I'll refactor that later_).

2023-09-21 08:12 UTC, ganigeorgiev commented on tools/auth/mailcow.go
> +		userApiUrl: "",
The fields can be removed as they will have an empty string by default.

2023-09-21 08:12 UTC, ganigeorgiev commented on tools/auth/mailcow.go
> + */
You can remove this comment (or move it to the `Mailcow` struct type comment).

Please also update the others comments to confront the common [godoc recommendations](https://go.dev/doc/comment) (aka. starting with the exposed identifier and use complete sentence(s)).

2023-09-21 08:12 UTC, ganigeorgiev commented on tools/auth/mailcow.go
> +	}
Avoid modifying directly the "original" extracted struct and instead apply the custom field transformation on the returned `AuthUser` field.

Also based on the code in https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/oauth/profile.php#L17, the username/id/identifier all shares the same value that it is different from the email (at least 2 different arrays and keys are used). Is the splitting really necessary in this case?

2023-09-21 08:12 UTC, ganigeorgiev commented on tools/auth/mailcow.go
> +		Active      int    `json:"active"`
Looking at their code in https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/oauth/profile.php it seems that the user (if exists) will be always "active", but just in case they decide to change that, let's add after the extraction a check and return an error in case the user is not "active".

2023-09-21 08:42 UTC, thisni1s commented on tools/auth/mailcow.go
> +	}
If the mailcow user has a mailbox, which is the case 99% of the time, the username/id/identifier fields are the email address even though the array has two different keys

2023-10-14 10:00 UTC, ganigeorgiev commented
@thisni1s Could you provide some guidance/steps how to create and test the mailcow OAuth2 app?

2023-10-14 11:58 UTC, ganigeorgiev commented
I've merged the PR with some minor nitpicks in the `develop` branch.

I figured out how to test it  - the OAuth2 app settings were buried under _System > Configuration > Access tab/dropdown > OAuth2 Apps_.

For the test I've used the live demo https://nightly-demo.mailcow.email/. There are some issues with its certificate as it is not recognized for some reason as part of the root chain, but other than that the integration seems to work fine.

The provider will be part of the next PocketBase v0.19.0 release soon.

2023-10-14 11:58 UTC, closed without merging

2023-10-14 13:58 UTC, thisni1s commented
Perfect, thank you